spring:
  application:
    name: item-service
  thymeleaf:
    cache: true 
  devtools:
    remote:
      context-path: /src/main    
    restart:
      enabled: true 
          
server:  port: 8001   
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

  